name = "DigitalSlideArchive"
uuid = "20296499-4daa-4357-ae8d-ba6e76525725"
authors = [
    "Kevin Bonham <kevin@bonham.ch>",
    "David Gutman <dagutman@gmail.com>",
]
version = "0.2.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2.23"
JSON3 = "1.14.0"
PythonCall = "0.9.23"
julia = "1.10"
